const TOKEN_EXPIRATION_TIME = '7d'
const BIO_LENGTH = 500
const PHOTO_URL_LENGTH = 50
const PHONE_NUM_LENGTH = 15
const IMAGE_SIZE = 1 * 1024 * 1024

module.exports = {
  TOKEN_EXPIRATION_TIME,
  BIO_LENGTH,
  PHOTO_URL_LENGTH,
  PHONE_NUM_LENGTH,
  IMAGE_SIZE
}
